name: VPN MASTER panel
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Выберите действие'
        required: true
        default: 'off'
        type: choice
        options:
        - 'off'
        - 'on'

permissions:
  contents: write

jobs:
  switch_vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update VPN File
        run: |
          if [ "${{ github.event.inputs.action }}" == "off" ]; then
            echo "Выключаем VPN в links.txt..."
            if [ -f "links.txt" ]; then
              sed -i 's/vless/OFF_vless/g' links.txt
              echo "Файл links.txt успешно отключен"
            else
              echo "Ошибка: файл links.txt не найден!"
              exit 1
            fi
          else
            echo "Включаем VPN в links.txt..."
            if [ -f "links.txt" ]; then
              sed -i 's/OFF_vless/vless/g' links.txt
              echo "Файл links.txt успешно включен"
            else
              echo "Ошибка: файл links.txt не найден!"
              exit 1
            fi
          fi
          
      - name: Save changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Сохраняем изменения только для файла links.txt
          git add links.txt
          
          # Проверяем, изменилось ли что-то в файле
          if git diff --staged --quiet; then
            echo "No changes to commit (возможно, в файле не было нужного текста)"
          else
            git commit -m "VPN Control: ${{ github.event.inputs.action }} for links.txt"
            git push
          fi
          
